run:
  deadline: 5m
  go: "1.18"
  skip-dirs: mocks,e2e

linters-settings:
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-anything: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      # The following checks were disabled because they don't work well with generics yet.
      - hugeParam
      - rangeValCopy
      - typeDefFirst
      - paramTypeCombine
  misspell:
    locale: US
  gosimple:
    go: '1.18'
  staticcheck:
    go: '1.18'
  unused:
    go: '1.18'

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    # fails because of some generic type
    #- gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - wsl
  fast: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

service:
  analyzed-paths:
    - src/...
  golangci-lint-version: 1.50.1