// Code generated by MockGen. DO NOT EDIT.
// Source: RedisRateLimiter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// IsRequestAllowed mocks base method.
func (m *MockRateLimiter) IsRequestAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRequestAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRequestAllowed indicates an expected call of IsRequestAllowed.
func (mr *MockRateLimiterMockRecorder) IsRequestAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRequestAllowed", reflect.TypeOf((*MockRateLimiter)(nil).IsRequestAllowed))
}
